name: Lint Markdown

on:
  pull_request:
  push:
    branches: [develop, main]

jobs:
  mdl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Rodar mdl
        run: bundle exec mdl content README.md
